import os
os.system("cls")
numeros=str(input("presione cualquie tecla para imprimir numeros del 1 al 10"))
print("1")
print("2")
print("3")
print("4")
print("5")
print("6")
print("7")
print("8")
print("9")
print("10")
